### ISSUE TITLE
Element can't be scrolled into view

### ISSUE THREAD

**Issue by JulioCesarAntonyFraga** [TreborNamor/TradingView_Machine_Learning#1]
So... Guys, I was trying to run the project and got some errors. The first one was that when searching for strategy_tester, there was no such element, I suppos,e since i got the following error:

```
strategy_tester = driver.find_elements_by_xpath("//*[@class='title-1C5azoXt']")[2]
IndexError: list index out of range
```

Then I looked for the element name in the inspection window at firefox and found the right name (I guess):

![image](https://user-images.githubusercontent.com/63599296/111796439-f0277b00-88a6-11eb-929d-262b6a3d4296.png)

It looks like now it started recognizing the element, but now i got this new error and I have no idea why. Can you guys help me?

`selenium.common.exceptions.ElementNotInteractableException: Message: Element <div class="title-37voAVwR"> could not be scrolled into view`

**Comment by JulioCesarAntonyFraga** [comment]
Looks like i had to change the elemment index to 0 instead of 2. Now I got some other elemments that I have to fix the name the script is looking for.

**Comment by JulioCesarAntonyFraga** [comment]
The elements the script is looking for are not correct. They may have changed. Can you guys please update?

**Comment by Andddyyyyy** [comment]
I'm having exactly the same issue as above, if the repo can be upated that'd be amazing!

**Comment by tmmatherne** [comment]
Same here.... incorrect xpath
It’s possible the class=“title-xxx” is unique to the stock being tested

I wouldn’t know how to fix this but sure TreborNamor could

**Comment by JulioCesarAntonyFraga** [comment]
I've been trying to fix it, and I kind of understood which elements they're trying to choose and all. At some point, it just can't find the element ".table-roles" or something like that ( I don't really remember the name). It just doesn't find it. I did tests, I replaced the code with the correct elements names, but in the end, this element just can't be find (even if it exists, and it actually does, at least it is shown in the page source code).

**Comment by tmmatherne** [comment]
I’ve managed to get it working. 
change the xpath location as you pointed out in your comment title- and also the innerInput one as well. Make sure you are logged into TradingView and that you only have stoploss checked within settings when running stoploss script.

**Comment by JulioCesarAntonyFraga** [comment]
> I’ve managed to get it working. 
> change the xpath location as you pointed out in your comment title- and also the innerInput one as well. Make sure you are logged into TradingView and that you only have stoploss checked within settings when running stoploss script. 

I've made an account but the script always open the browser with it logged out. 

I will try to apply the things you told me tomorrow. Thank you for the help.

**Comment by tmmatherne** [comment]
Ahh yes. I had that same issue as well. Here is the fix for that. Go to Firefox address bad and type the following 

about:preferences#privacy<enter> 
 The button next to History, select Use Custom Settings.

Turn off Always Use Private Browsing Mode Turn on Remember My Browsing And Download History At the bottom of the page, turn on Clear History When Firefox Closes. At the far right, press the Settings button. Turn on ONLY Cache and Form And Search History leaving the others off.


This will keep you logged into tradingview

**Comment by JulioCesarAntonyFraga** [comment]
> Ahh yes. I had that same issue as well. Here is the fix for that. Go to Firefox address bad and type the following 
> 
> about:preferences#privacy<enter> 
>  The button next to History, select Use Custom Settings.
> 
> Turn off Always Use Private Browsing Mode Turn on Remember My Browsing And Download History At the bottom of the page, turn on Clear History When Firefox Closes. At the far right, press the Settings button. Turn on ONLY Cache and Form And Search History leaving the others off.
> 
> 
> This will keep you logged into tradingview

Thank you, man! I appreciate your help.

**Comment by Andddyyyyy** [comment]
Thanks for the help guys! I'm getting top to the point now ehere it will open the settings box to upodate the Stop loss/Take profit values but get this error:

Loading script...
script has timed out.
Traceback (most recent call last):
  File "C:\Users\Andyf\OneDrive\Desktop\TradingView_Machine_Learning-master\scripts\takeprofit_linear.py", line 76, in <module>
    run_script(webdriver.driver)
  File "C:\Users\Andyf\OneDrive\Desktop\TradingView_Machine_Learning-master\scripts\takeprofit_linear.py", line 41, in run_script
    best_key = find.best_key()
  File "C:\Users\Andyf\OneDrive\Desktop\TradingView_Machine_Learning-master\functions\find.py", line 5, in best_key
    best_in_dict = max(profits, key=profits.get)
ValueError: max() arg is an empty sequence

Any ideas?

**Comment by tmmatherne** [comment]
Did you save the root Directory or Local?  Not sure if ut matters but I used the root directory
![image](https://user-images.githubusercontent.com/11143405/112329544-4b7db280-8c85-11eb-949a-db2bae7f10dd.png)

**Comment by batuhan3526** [comment]
Hello Are u guys got this error ? Could u help me ?
![error](https://user-images.githubusercontent.com/52297554/113473411-fce4cb00-9471-11eb-8261-aa96cae61ed6.PNG)
![error3](https://user-images.githubusercontent.com/52297554/113473414-02421580-9472-11eb-9cc9-91a1f5ad4a4b.PNG)
@tmmatherne @JulioCesarAntonyFraga @Andddyyyyy

**Comment by TreborNamor** [comment]
hello everyone, it looks like the elements on Tradingview had changed. I updated the elements and added some extra fixes to script. If you guys are still having problems please download the new repository.

**Comment by tmmatherne** [comment]
thanks @TreborNamor
