### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Jacksparrowoo1** [TreborNamor/TradingView_Machine_Learning#13]
![error help](https://user-images.githubusercontent.com/84126082/118104753-2857bf80-b3f9-11eb-89ab-a195e42a65e5.jpg)
can anyone help

**Comment by layhau** [comment]
me too having the exact same problem :(

**Comment by TreborNamor** [comment]
the click.py file was outdated but I just updated the script to fix that error. You can copy and paste the click.py on my GitHub into your script to get everything running properly.
