### ISSUE TITLE
error

### ISSUE THREAD

**Issue by empadv** [TreborNamor/TradingView_Machine_Learning#14]
ModuleNotFoundError: No module named 'functions'
PS D:\TradingView_Machine_Learning-master> 

this is the error any idea what i should do

**Comment by Grantmac75** [comment]
I get the same.  Any solutions?

**Comment by Deanagage** [comment]
Indeed, same here.

**Comment by SteveL1** [comment]
I think you need to copy the python script to the parent folder and run it from there

**Comment by decipher1614** [comment]
Hi,

I have successfully able to get the best setting. But, it is not showing results as in a youtube video. Instead, it shows error:    
"selenium.common.exceptions.ElementNotInteractableException: Message: Element <div class="title-37voAVwR"> could not be scrolled into view"

**Comment by TreborNamor** [comment]
> Hi,
> 
> I have successfully able to get the best setting. But, it is not showing results as in a youtube video. Instead, it shows error:
> "selenium.common.exceptions.ElementNotInteractableException: Message: Element
> 
> could not be scrolled into view"

I fixed this issue today. You should be able to the script properly now.
