### ISSUE TITLE
A different issue

### ISSUE THREAD

**Issue by Grantmac75** [TreborNamor/TradingView_Machine_Learning#15]
First;y I get an error that it can't find the Functions.
I fixed that by copying the scripts into the main folder directory and add a __main__.py to the funtions directory.

Now I get this error.
![Capture](https://user-images.githubusercontent.com/61583258/120186361-c13e6580-c256-11eb-9eb0-094b732dc8cd.JPG)

I really don't understand what I have done wrong.  I followed your instructions but it doesn't seem to work as yours does on Youtube.

Thanks for your help.  Awesome work by the way.

**Comment by TreborNamor** [comment]
Hello, I updated the click.py file to fix this error. Can you give it a try to see if it works for you? thank you.

**Comment by Grantmac75** [comment]
Hi Trebor,  Thank you, that seems to be working now for me.  Can i ask what you changed? just curious for my own education.  Thanks again, very good work.

**Comment by TreborNamor** [comment]
The error was coming from a function in the click.py file. The function
called strategy tester had an web element that selenium could not find. I
corrected the problem by adding a few lines of code so selenium can find
the web element.
