### ISSUE TITLE
ModuleNotFoundError: No module named 'functions'

### ISSUE THREAD

**Issue by Data64X** [TreborNamor/TradingView_Machine_Learning#16]
Hi TreborNamor,

Same as issue 13 but do not see the fix?
I pulled the ZIP down today.

Is this an environment config issue?

Cheers Data64X

Traceback (most recent call last):
File "C:/Users/ blah blah /TradingView_Machine_Learning-master/scripts/takeprofit_liner.py", line 4, in <module> import click.py
File "C:\Users\ blah blah \TradingView_Machine_Learning-master\scripts\click.py", line 8, in <module> from functions.webdriver import driver
ModuleNotFoundError: No module named 'functions'

**Comment by TreborNamor** [comment]
From the file you trying to open it looks like you might have the old
version of my script. I updated a new script today. To get it working, you
can download the zip file on GitHub and extract to your Desktop or directly
on your C drive. In Pycharm, you can open project and pip install the
requirements to run script. Hope this helps

**Comment by Data64X** [comment]
Upgrading to the latest version of Pycharm solved the above but introduced  an error with Powershell when running any of the three scripts.  Have up graded Firefox to the latest, slim information out there on the following have you seen this with your code? 
====== WebDriver manager ======
'Powershell' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TreborNamor** [comment]
I haven't experienced this powershell error before but It sounds like you are missing an environment variable. Try checking out this forum on StackOverFlow.

https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr/29778651#29778651

**Comment by Data64X** [comment]
Path was the problem working well thank you. Are you active on your telegram channel? , will send a bit of BTC.

**Comment by TreborNamor** [comment]
Thank You, I'm am often active on Telegram. I actually have a AI bot that a lot of people love to trade if you'd like to join.
As well, my here is my BTC address. Thank you very much for the donations. This really does help me focus on updating these projects. Glad they are useful to you.

BTC address: 3EAjyQpGZ6YDeYayLyeVcKVnkj8pit4rTF
Telegram Group: https://t.me/joinchat/BPVwDm2L-QQ0OTI5
