### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by allanglez** [TreborNamor/TradingView_Machine_Learning#2]
![image](https://user-images.githubusercontent.com/44878475/112559389-288af580-8d8e-11eb-9e4a-65267b61af1f.png)

**Comment by allanglez** [comment]
Fixed the `xpath("//*[@class='title-37voAVwR']")`  problem changin the title, but getting this error now at stoploss function.

**Comment by darkmage20** [comment]
Open Tradingview, right click on the strategy input for stop loss %.  
![bot](https://user-images.githubusercontent.com/39513473/112920408-e556bc80-90d6-11eb-8f69-afde13ccc17c.jpg)

change lines 73,74,83,84 with the sequence you got from right clicking

**Comment by batuhan3526** [comment]
Hello Are u guys got this error ? Could u help me ?
![error](https://user-images.githubusercontent.com/52297554/113473411-fce4cb00-9471-11eb-8261-aa96cae61ed6.PNG)
![error3](https://user-images.githubusercontent.com/52297554/113473414-02421580-9472-11eb-9cc9-91a1f5ad4a4b.PNG)

@darkmage20 @allanglez

**Comment by TreborNamor** [comment]
> Open Tradingview, right click on the strategy input for stop loss %.
> ![bot](https://user-images.githubusercontent.com/39513473/112920408-e556bc80-90d6-11eb-8f69-afde13ccc17c.jpg)
> 
> change lines 73,74,83,84 with the sequence you got from right clicking
> 
> make sure you change for both input boxes

Darkmage20 is on the right path. The element for the stoploss had changed. I recently updated the script today for anyone still having trouble with this issue.

**Comment by Jacksparrowoo1** [comment]
![error help](https://user-images.githubusercontent.com/84126082/118104646-052d1000-b3f9-11eb-9076-46f7c7d0ca39.jpg)
please anyone can help me
