### ISSUE TITLE
can't find #3, find folder

### ISSUE THREAD

**Issue by driesdep** [TreborNamor/TradingView_Machine_Learning#3]
Hello,
I have been looking for a find folder on pycharm, but there is no anymore ?
Where do i need to paste my webfolder file ?

I don't understand this very well ...

If you could give me more info ?
thx
dries

**Comment by driesdep** [comment]
found it already . I was looking into my installed pycharm application for "folder"
Thanks

**Comment by driesdep** [comment]
After some strugling with the modules working, i finaly got it running. But this gave me also an error.
On line 68 i believe a problem with a tuple.
But i don't know what the problem should be.
I habe attached the program error on the issue here.
If you could help me out it would be so nice )

Thank you
Dries
![Function68](https://user-images.githubusercontent.com/81444996/112723031-dd4b2100-8f0c-11eb-8f88-53d316a6b968.png)
![Functions3](https://user-images.githubusercontent.com/81444996/112723035-e50ac580-8f0c-11eb-8f15-68a16c68b289.png)

**Comment by TreborNamor** [comment]
SyntaxError: invalid syntax.

It looks like you have an old version of Python that is causing the syntax error. You can download and update your Python to the latest version here. https://www.python.org/downloads/

As well, please download my updated repository. There has been some changes. Thanks!
