### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by batuhan3526** [TreborNamor/TradingView_Machine_Learning#4]
Hello I downloaded code firefox and change firefox profile. 

Right now  I got this error. And I have no exprience in Scraping (especially with firefox). Guys What should I do?

![error](https://user-images.githubusercontent.com/52297554/113429203-ce6adf80-93e0-11eb-8c0e-29340d1f4da2.PNG)

![error3](https://user-images.githubusercontent.com/52297554/113431274-2c4cf680-93e4-11eb-9e16-add3025f4b26.PNG)

@TreborNamor

**Comment by TreborNamor** [comment]
There has been some changes on the Tradingview website which caused the script not to work. I recently fixed them today for any one having issues please download the new script. It will take care of the error you were experiencing.
