### ISSUE TITLE
selenium.common.exceptions.ElementNotInteractableException

### ISSUE THREAD

**Issue by batuhan3526** [TreborNamor/TradingView_Machine_Learning#5]
Hello ı downloaded latest code and ı got this error. What should ı do ? By the way thx to latest code @TreborNamor 
![errorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr](https://user-images.githubusercontent.com/52297554/113503582-7e546000-953b-11eb-9878-fb4dd4c04234.PNG)

**Comment by batuhan3526** [comment]
Wrong alert I Handled it. Will you publish a code that can optimize both stop loss and take profit values?

**Comment by TreborNamor** [comment]
Yeah, I'll get to working on it. I should have it up soon.
