### ISSUE TITLE
can't find '__main__'  ???

### ISSUE THREAD

**Issue by m9tz** [TreborNamor/TradingView_Machine_Learning#6]
Hi
first thank for the great work!!!

I get this in pycharm: 
```
/home/mhi/anaconda3/envs/TradingView_Machine_Learning/bin/python: can't find '__main__' module in '/home/mhi/PycharmProjects/TradingView_Machine_Learning'

Process finished with exit code 1
```
in the linux terminal and conda enviroment:

```
(TradingView_Machine_Learning) mhi@coha:~/PycharmProjects/TradingView_Machine_Learning$ python3 scripts/stoploss_linear.py 
Traceback (most recent call last):
  File "scripts/stoploss_linear.py", line 3, in <module>
    from functions import click, webdriver, show_me, get, find
ModuleNotFoundError: No module named 'functions'
```
and that at the normal linux terminal:
```
mhi@coha:~/PycharmProjects/TradingView_Machine_Learning$ python3 scripts/stoploss_linear.py 
Traceback (most recent call last):
  File "/home/mhi/PycharmProjects/TradingView_Machine_Learning/scripts/stoploss_linear.py", line 3, in <module>
    from functions import click, webdriver, show_me, get, find
ModuleNotFoundError: No module named 'functions'
```

ok I'am new to pychame! I have to activate the conda enviroment manual in the pychame terminal and the webdriver-manager package can'tbeinstalled via conda only via pip.

but the results from the normal linux-system terminal also failed all modulules are there install with pip in the os default interpreter path

**Comment by TreborNamor** [comment]
ModuleNotFoundError: No module named 'functions'


When you are running script in the terminal you might be running
script in the wrong folder. Python is having trouble finding your
functions.py file

**Comment by bertinlr** [comment]
Is this a related issue? I have the following error:
Loading script...
script has timed out.
Traceback (most recent call last):
  File "/Users/bertinlr/Downloads/TradingView_Machine_Learning-master/scripts/takeprofit_linear.py", line 76, in <module>
    run_script(webdriver.driver)
  File "/Users/bertinlr/Downloads/TradingView_Machine_Learning-master/scripts/takeprofit_linear.py", line 41, in run_script
    best_key = find.best_key()
  File "/Users/bertinlr/Downloads/TradingView_Machine_Learning-master/functions/find.py", line 5, in best_key
    best_in_dict = max(profits, key=profits.get)
ValueError: max() arg is an empty sequence

Process finished with exit code 1

During the weekend was able to run it successfully.

**Comment by TreborNamor** [comment]
ValueError: max() arg is an empty sequence.

This error is because while script was running, it wasn't able to store any data values. So the best_key variable wasn't able to run .max() method. To fix this make sure your click.py file is the same as my new click.py file.
