### ISSUE TITLE
two or more tradingview strategy parameters change simultaneously (enable two in the youtube video)

### ISSUE THREAD

**Issue by asyildiz3363** [TreborNamor/TradingView_Machine_Learning#9]
Hi Robert,
It will be very appreciated If you publish a script to do that.

May be you can explain how to tailor the script to test our own strategies.

Thanks in advance!

**Comment by TreborNamor** [comment]
hello! I added this project to give you the ability to change parameters simultaneously. You will probably have to update this project since a lot of files have been modified recently. If you have any more questions or recommendations, let me know!  😃

**Comment by asyildiz3363** [comment]
Hello, I updated the files. It is working when I use your strategy, but I want to tailor it. For example, what changes should I make in scripts to optimize the length of a simple 2 EMA cross strategy.
Thanks!

**Comment by TreborNamor** [comment]
That's a good question, I'll create a template that you can add to any
strategy. It's pretty much just adding the stoploss and take profit inputs
into script. I'll get started on it today.

**Comment by asyildiz3363** [comment]
It would be apreciated. Thanks!

**Comment by asyildiz3363** [comment]
I tried the script with another strategy. It is still working, even I did not change anything. It changes first two inputs after opening the settings. If settings left in the properties tab, it also tried to change the initial capital and order size. I did not understand the logic here.

**Comment by TreborNamor** [comment]
I like how you are starting to understand the code. The python file does
have access to the first two inputs on TradingView website. I had updated
the tradingview strategy on Github last night but I have not fully updated
the python script. I will need to set some rules to make sure it recognizes
that it is on the input tab to fix the problem. What you need to apply from
the MACD/RSI is the top part of the script where it says long strategy,
short strategy, date range to your script. Then lastly copy the strategy
code down below. Now that you've done that to your strategy you'll be able
to use the python script on any of your strategies. Just make sure at the
strategy code to create you own buy and sell signals.

If you still are having trouble don't worry I'll create a new video for you
showing the new updates as well as how to apply code to any strategy.
